### ISSUE TITLE
Map grid property to standard names (e.g. porosity)

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/fmu-dataio#266] opened 2022-11-07 12:19 UTC

**Comment by jcrivenaes** [comment] 2022-11-10 20:03
Could you elaborate on use case and eventual what standard names should be?

**Comment by anders-kiaer** [comment] 2022-11-23 12:30
The use case was brought up by @HansKallekleiv, and is typically to co-visualize some property (`porosity`, `depth`, ...) from RMS and Eclipse. The challenge today is that the properties have different names in the different tools (e.g. `PORO`, `porosity`, `PORV` - sometimes also indicating if it is effective or total, sometimes you need to refer to the manual to know...)

**Comment by perolavsvendsen** [comment] 2022-11-30 12:33
Is this `data.content`?
Assume for now that grid properties are exported 1 property per file.
Perhaps just define the most common properties?
`porosity`, `permeability`, etc.?
- [ ] Discuss/refine this. @HansKallekleiv @anders-kiaer @jcrivenaes

**Comment by jcrivenaes** [comment] 2022-12-06 09:10
- porosity
- permeability ... anisotropy?
- water_saturation [Water saturation]
- oil_saturation   
- gas_saturation
- zone (check SMDA)
- facies
- ntg
- hcpv
- stoiip/stooip
- giip
- hc_thickness ?
- ...

Avoid `depth` as default?

**Comment by perolavsvendsen** [comment] 2022-12-08 09:56
Agree that "depth" should be avoided as default. Already polluting the stored data in Sumo. The combination of white-listing content and having a default quickly leads to using `depth` for everything that is not in the list. Example from current implementation on Snorre is that RFT-data is tagged with `content: depth`. 

#277

**Comment by jcrivenaes** [comment] 2022-12-08 10:28
Yes we should probably let `content` be a mandatory field instead

**Comment by mferrera** [comment] 2024-12-12 11:38
Closing this as a duplicate of #734 which is tied to some more recent discussion on this.

**Closed by mferrera** 2024-12-12 11:38 UTC
Labels: Data definitions
